jobs:
- job: Windows_CI_Dev
  pool: Win-CPU
  steps:
    - task: BatchScript@1
      inputs:
        filename: build.bat
        arguments: ' --enable_pybind --use_mkldnn --use_mklml --use_openmp --build_shared_lib --build_csharp --enable_onnx_tests'
        workingFolder: "$(Build.SourcesDirectory)"

    - task: CmdLine@1
      displayName: 'Clean build folders/files'
      inputs:
        filename: rd
        arguments: '/s /q $(Agent.BuildDirectory)'
      continueOnError: true
      condition: always()
